import "./globals.css";
import styles from "@/styles/footer.module.css";
import { Toaster } from "sonner";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <div className={styles.policy}>
          © 2023 drestein.it All rights reserved.
        </div>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
